### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by boistordu** [fvalle1/haveibeenpwned#5]
Every mail that I know have been powned is not returning as been powned since the beginning of your bot creation

**Comment by fvalle1** [comment]
May you try make an api call to the website (https://haveibeenpwned.com/API/v2) with one of those emails, please?

So we can know if the problem is the bot itself or the api

Thank you 

Filippo

**Comment by boistordu** [comment]
fair enough, will do when I finish my coding .

**Comment by boistordu** [comment]
can you try later? I'm running into cloudflare access denied thing

**Comment by boistordu** [comment]
have you test it? spare me adoubt here. It s your bot the @haveibeenpwned_bot ? right?

**Comment by fvalle1** [comment]
Yes it is that bot!

No, I have not found time yet!;-)

Filippo Valle

**Comment by fvalle1** [comment]
May you tell me (in pvt) which gave you problem?


Filippo Valle

**Comment by boistordu** [comment]
and how would I speak to you in private dear friend?

**Comment by fvalle1** [comment]
There is an email on my profile!

Filippo Valle

**Comment by boistordu** [comment]
now there is because before i couldn't see it!

**Comment by fvalle1** [comment]
There was an error in internal API, thank you for reporting
